name: mgr
channels:
  - defaults
  - bioconda
  - daler
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.0
  - _sysroot_linux-64_curr_repodata_hack=3
  - asttokens=2.4.1
  - binutils_impl_linux-64=2.38
  - binutils_linux-64=2.38.0
  - biopython=1.78
  - blas=1.0
  - blast=2.15.0
  - bottleneck=1.3.7
  - bowtie=1.3.1
  - bowtie2=2.5.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bwidget=1.9.16
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - cairo=1.16.0
  - clustalw=2.1
  - comm=0.2.2
  - contourpy=1.2.0
  - curl=7.88.1
  - cycler=0.11.0
  - debugpy=1.8.1
  - decorator=5.1.1
  - entrez-direct=21.6
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - fastp=0.23.4
  - fontconfig=2.14.2
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gffread=0.12.7
  - gfortran_impl_linux-64=11.2.0
  - gfortran_linux-64=11.2.0
  - glib=2.69.1
  - graphite2=1.3.14
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - harfbuzz=4.3.0
  - htseq=2.0.3
  - htslib=1.17
  - icu=58.2
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - isa-l=2.30.0
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - kernel-headers_linux-64=3.10.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.88.1
  - libdeflate=1.13
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libhwloc=2.8.0
  - libiconv=1.17
  - libidn2=2.3.4
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.9.14
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - macs2=2.2.9.1
  - make=4.2.1
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.7
  - mfold=3.6
  - munkres=1.1.4
  - ncbi-vdb=3.1.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - packaging=23.2
  - pandas=2.2.1
  - pango=1.50.7
  - parso=0.8.4
  - pcre=8.45
  - pcre2=10.37
  - perl=5.32.1
  - perl-archive-tar=2.40
  - perl-carp=1.38
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.105
  - perl-encode=3.19
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.201
  - perl-io-zlib=1.14
  - perl-json=4.10
  - perl-json-xs=2.34
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.62
  - perl-types-serialiser=1.01
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.1
  - pixman=0.40.0
  - platformdirs=4.2.1
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - pyparsing=3.0.9
  - pysam=0.21.0
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyzmq=26.0.2
  - r-base=4.2.0
  - readline=8.2
  - samtools=1.18
  - scipy=1.12.0
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - star=2.7.11a
  - sysroot_linux-64=2.17
  - tbb=2021.8.0
  - tk=8.6.12
  - tktable=2.10
  - tornado=6.4
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - viennarna=2.6.4
  - wcwidth=0.2.13
  - wget=1.21.4
  - wheel=0.41.2
  - xz=5.2.10
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5

